<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ClinicalInquiries [

<!ELEMENT ClinicalInquiries (record+)>
<!ELEMENT record (url,question,answer)>
<!ELEMENT answer (snip*)>
<!ELEMENT snip (sniptext,sor,long*)>
<!ELEMENT long (longtext,ref*)>

<!ELEMENT url (#PCDATA)>
<!ELEMENT question (#PCDATA)>
<!ELEMENT sniptext (#PCDATA)>
<!ELEMENT longtext (#PCDATA)>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT sor (#PCDATA)>

<!ATTLIST ClinicalInquiries version CDATA #REQUIRED>  <!--version="1.0"-->
<!ATTLIST record id CDATA #REQUIRED>        <!--id="1868"-->
<!ATTLIST snip id CDATA #REQUIRED>          <!--id="1"-->
<!ATTLIST long id CDATA #REQUIRED>          <!--id="1_1"-->
<!ATTLIST sor type CDATA #REQUIRED>         <!--type="A"-->
<!ATTLIST ref id CDATA #REQUIRED>           <!--id=PbMedID-->
<!ATTLIST ref abstract CDATA #REQUIRED>     <!--abstract="Abstracts/PbMedId.xml"-->
<!ATTLIST ref fulltext CDATA #IMPLIED>      <!--abstract="Abstracts/PbMedId.xml"-->
<!ATTLIST record comment CDATA #IMPLIED>
<!ATTLIST answer comment CDATA #IMPLIED>
<!ATTLIST snip comment CDATA #IMPLIED>
<!ATTLIST long comment CDATA #IMPLIED>
<!ATTLIST sor comment CDATA #IMPLIED>

]>

<ClinicalInquiries version="1.0">
	<record id="1853">
		<url>http://www.jfponline.com/Pages.asp?AID=1853&amp;issue=January_2005&amp;UID=</url>
		<question>Does neonatal circumcision decrease morbidity?</question>
		<answer>
			<snip id="1">
				<sniptext>Evidence suggests that neonatal circumcision decreases the incidence of childhood urinary tract infections, phimosis, paraphimosis, balanitis and other genital dermatoses, invasive penile cancer, and the sexually transmitted diseases human papilloma virus (HPV) and HIV.</sniptext>
				<sor type="B">based on case control and cohort studies</sor>
				<long id="1_5">
					<longtext>In a series of 89 men with penile cancer, only 2 had been circumcised in infancy, while 87 were uncircumcised.</longtext>
					<ref id="10724196" abstract="Abstracts/10724196.xml">Mallon E, Hawkins D, Dinneen M, et al. Circumcision and genital dermatoses. Arch Dermatol 2000; 136: 350-354.</ref>
				</long>
				<long id="1_4">
					<longtext>Evidence from case series supports the protective effect of circumcision on the rates of penile cancer. A review of 592 cases of penile cancer revealed that none of those affected had been circumcised in infancy.</longtext>
					<ref id="11732129" abstract="Abstracts/11732129.xml">Lerman SE, Liao JC. Neonatal circumcision. Pediatr Clin North Am 2001; 48: 1539-557.</ref>
				</long>
				<long id="1_3">
					<longtext>A randomized controlled trial of circumcision for UTI prevention was not during the neonatal period (average age was 30 months) and focused on secondary prevention. It demonstrated a statistically significant decrease in the rate of bacteriuria. The long-term effect on UTI incidence, renal scarring, and subsequent complications such as hypertension and end-stage renal disease is unknown.</longtext>
					<ref id="11793114" abstract="Abstracts/11793114.xml">Nayir A. Circumcision for the prevention of significant bacteriuria in boys. Pediatr Nephrol 2001; 16: 1129-1134. Erratum in: Pediatr Nephrol. 2002; 17: 307.</ref>
				</long>
				<long id="1_2">
					<longtext>The number of male infants that need to be circumcised to prevent 1 UTI is estimated to be between 44 and 100.</longtext>
					<ref id="1853_2_NOT_FOUND" abstract="Abstracts/NO_ABSTRACT">Sethi N, Schwierling K, Kim J, et al. Newborn circumcision and urinary tract infections. Pediatrics 2001; 107: 212.</ref>
					<ref id="10617731" abstract="Abstracts/10617731.xml">Christakis DA, Harvey E, Zerr DM, Feudtner C, Wright JA, Connell FA. A trade off analysis of routine newborn circumcision. Pediatrics 2000; 105: 246-249.</ref>
				</long>
				<long id="1_1">
					<longtext>Observational studies have shown at least a 10- to 12-fold increase in urinary tract infections (UTIs) in uncircumcised male infants compared with their circumcised counterparts.</longtext>
					<ref id="10742334" abstract="Abstracts/10742334.xml">Wiswell TE. The prepuce, urinary tract infections, and the consequences. Pediatrics 2000; 105: 860-862.</ref>
				</long>
			</snip>
			<snip id="2">
				<sniptext>The benefits of decreased incidence of HPV and HIV infections go beyond the index patient and have public health implications on the transmission of these diseases.</sniptext>
				<sor type="B">None</sor>
				<long id="2_1">
					<longtext>In a meta-analysis of 7 case-control studies, penile HPV was detected 2.7 times more often in uncircumcised men after controlling for confounders. In this same meta-analysis, monogamous female partners of high-risk circumcised men (men with more than 6 lifetime partners) had a lower risk of cervical cancer than women whose high-risk partner was uncircumcised (adjusted odds ratio=0.42; 95% confidence interval [CI], 0.23-0.79).</longtext>
					<ref id="1878787" abstract="Abstracts/1878787.xml">Schoen EJ. The relationship between circumcision and cancer of the penis. CA Cancer J Clin 1991; 41: 306-309.</ref>
				</long>
				<long id="2_2">
					<longtext>A meta-analysis of 15 observational studies in Africa, with adjustment for potential confounding factors, found that circumcision decreased the risk of acquiring HIV by more than half (relative risk [RR]=0.42; 95% CI, 0.34-0.54).</longtext>
					<ref id="10699138" abstract="Abstracts/10699138.xml">Schoen EJ, Oehrli M, Colby C, Machin G. The highly protective effect of newborn circumcision against invasive penile cancer. Pediatrics 2000; 105: E36.</ref>
				</long>
				<long id="2_3">
					<longtext>A recent prospective study from India showed a strong protective effect of circumcision against HIV infection (RR=0.15; 95% CI, 0.04-0.62). This study found no protective effect of circumcision against herpes, syphilis, or gonorrhea, suggesting a biological rather than a behavioral explanation for the protective effect of circumcision against HIV.</longtext>
					<ref id="11948269" abstract="Abstracts/11948269.xml">Castellsague X, Bosch FX, Munoz N, et al. Male circumcision, penile human papillomavirus infection, and cervical cancer in female partners. N Engl J Med 2002; 346: 1105-1112.</ref>
				</long>
				<long id="2_4">
					<longtext>Circumcision may also be protective against genital dermatoses; a case-control study found an age-adjusted odds ratio of 3.2 (95% CI, 2.3-4.6) for penile skin diseases in uncircumcised men compared with circumcised men.</longtext>
					<ref id="15051285" abstract="Abstracts/15051285.xml">Reynolds SJ, Shepherd ME, Risbud AR, et al. Male circumcision and risk of HIV-1 and other sexually transmitted infections in India. Lancet 2004; 363: 1039-1040.</ref>
				</long>
			</snip>
			<snip id="3">
				<sniptext>A decrease in HPV incidence and transmission may lead to a lower incidence of cervical cancer.</sniptext>
				<sor type="B">None</sor>
				<long id="3_1">
					<longtext>In a meta-analysis of 7 case-control studies, penile HPV was detected 2.7 times more often in uncircumcised men after controlling for confounders. In this same meta-analysis, monogamous female partners of high-risk circumcised men (men with more than 6 lifetime partners) had a lower risk of cervical cancer than women whose high-risk partner was uncircumcised (adjusted odds ratio=0.42; 95% confidence interval [CI], 0.23-0.79).</longtext>
					<ref id="1878787" abstract="Abstracts/1878787.xml">Schoen EJ. The relationship between circumcision and cancer of the penis. CA Cancer J Clin 1991; 41: 306-309.</ref>
				</long>
			</snip>
			<snip id="4" comment="Author's opinion.">
				<sniptext>While there appears to be some evidence for reduced morbidity with routine circumcision, decisions regarding routine neonatal circumcision requires balancing risks and benefits of the procedure with the alternatives in the context of social, familial, and religious beliefs.</sniptext>
				<sor type="">None</sor>
				<long id="4_1" comment="Loosly related to the snip.">
					<longtext>A conservative estimate of the post-neonatal childhood circumcision rate for purely medical reasons is 2% to 5%; estimates go as high as 7% to 10%.</longtext>
					<ref id="11089625" abstract="Abstracts/11089625.xml">Weiss HA, Quigley MA, Hayes RJ. Male circumcision and risk of HIV infection in sub-Saharan Africa: a systematic review and meta-analysis. AIDS 2000; 14: 2361-2370.</ref>
				</long>
			</snip>
		</answer>
	</record>
	<record id="1948">
		<url>http://www.jfponline.com/Pages.asp?AID=1948&amp;issue=June_2005&amp;UID=</url>
		<question>Which imaging modality is best for suspected stroke?</question>
		<answer>
			<snip id="1">
				<sniptext>Patients exhibiting stroke symptoms should have brain imaging immediately within 3 hours of symptom onset.</sniptext>
				<sor type="A">based on systematic review</sor>
				<long id="1_1">
					<longtext>The British National Health Service Health Technology Assessment (HTA) Programme published a systematic review on optimal brain imaging strategies for the diagnosis of stroke in July 2004. The HTA searched Medline and EMBASE from 1980 to 1999 and found 1903 studies relevant to diagnostic imaging for stroke. Only 25 studies reported the type of stroke diagnosed and the imaging reference standard. Thirteen of these 25 studies describe the time interval from symptom onset to imaging. The Programme advises &quot;scan all immediately&quot; for diagnosing new neurological deficits with the understanding that CT scans were most available and cost-effective.</longtext>
					<ref id="14731377" abstract="Abstracts/14731377.xml">Wardlaw JM, Keir SL, Seymour J, et al. What is the best imaging strategy for acute stroke?. Health Technol Assess 2004; 8: 1-180.</ref>
				</long>
			</snip>
			<snip id="2">
				<sniptext>In the first 3 hours after a suspected cerebrovascular accident CVA, noncontrast head computerized tomography CT is the gold standard for diagnosis of acute hemorrhagic stroke.</sniptext>
				<sor type="C">based on expert panel consensus</sor>
				<long id="2_1">
					<longtext>In 2003, the Stroke Council, appointed by the American Heart Association, stated: &quot;For most cases and at most institutions, CT remains the most important brain imaging test. A physician skilled in assessing CT studies should be available to interpret the scan.&quot; The Stroke Council further recommends that &quot;in patients seen within 6 hours of onset, CT currently may be preferred as the first imaging study because MRI detection of acute intracerebral hemorrhage has not been fully validated.</longtext>
					<ref id="12677087" abstract="Abstracts/12677087.xml">Adams HP, Adams RJ, Brott T, et al. Guidelines for the early management of patients with ischemic stroke. Stroke 2003; 34: 1056-1083.</ref>
				</long>
			</snip>
			<snip id="3" comment="This snip could be joined to snip2.">
				<sniptext>The sensitivity for hemorrhage declines steeply 8 to 10 days after the event. Eligibility guidelines for acute thrombolytic therapy are currently based on use of CT to rule out acute hemorrhagic stroke.</sniptext>
				<sor type="">None</sor>
				<long id="3_1" comment="This long could be joined to snip2">
					<longtext>The HTA performed a prospective cohort study comparing CT with MRI obtained in random order on the day of presentation. They enrolled 228 patients presenting to a general hospital with stroke symptoms: (1) lasting longer than 1 day, but causing little or no decrease in function, or (2) lasting longer than 5 days. The mean time from onset of symptoms to scanning was 21.5 days. CT detected hemorrhagic stroke in 50%, and late hemorrhagic transformation in 20%, of those patients found to have hemorrhagic stroke on MRI, which was considered the criterion standard of chronic stroke diagnosis. The earliest hemorrhagic stroke missed by CT was 11 days old, and the latest hemorrhage correctly identified by CT was 14 days old.</longtext>
				</long>
			</snip>
			<snip id="4">
				<sniptext>Magnetic resonance imaging MRI may be equally accurate in diagnosing an acute hemorrhagic stroke if completed within 90 minutes of presentation for patients whose symptoms began fewer than 6 hours earlier.</sniptext>
				<sor type="B">based on a single high-quality cohort study</sor>
				<long id="4_1">
					<longtext>A prospective cohort study comparing imaging modalities in the acute time frame has been published. The study enrolled 129 patients with stroke symptoms of less than 3 hours, as well as 71 patients with between 3 and 6 hours of symptoms. Patients underwent multimodal MRI (including gradient recalled echo and diffusion-weighted imaging) and noncontrast CT within 90 minutes of presentation. Two stroke specialists and 2 neuroradiologists, masked to clinical information, read the scans independently at a later date. Interrater reliability was good (= 0.75-0.94) for identifying acute hemorrhage. There was 96% concordance between the MRI and CT interpretations. The 4 hemorrhages &quot;missed&quot; by CT were hemorrhagic transformations of acute infarct, and the 4 hemorrhages &quot;missed&quot; by MRI were misclassified as chronic when they were acute. The clinical implications of this study are uncertain. Without recognition of 1 imaging modality as the reference standard, it is difficult to say whether a hemorrhage &quot;missed&quot; on CT was a false negative on CT or a false positive on MRI.</longtext>
					<ref id="14731377" abstract="Abstracts/14731377.xml">Wardlaw JM, Keir SL, Seymour J, et al. What is the best imaging strategy for acute stroke?. Health Technol Assess 2004; 8: 1-180.</ref>
				</long>
			</snip>
			<snip id="5">
				<sniptext>MRI is more sensitive than CT for ischemic stroke in the first 24 hours of symptoms.</sniptext>
				<sor type="B">based on systematic review of low-quality studies with consistent findings</sor>
				<long id="5_1">
					<longtext>The HTA found a wide range of sensitivities for CT and MRI for both hemorrhagic and ischemic strokes at different time periods and noted that the quality of most of these studies was poor. Most of the studies identified were performed in academic stroke centers and had small sample sizes. Interpretation was masked in only 58% of studies. Few data were available on interobserver reliability, and neuroradiologists usually interpreted images. Two studies, totaling 165 patients, compared CT and MRI scans performed on the same day. However, the most &quot;acute&quot; time period reported was within 48 hours from symptom onset; neither study reported the order in which scans were performed, and only 1 study masked the neuroradiologist to the interpretation of the other modality. Time since symptom onset for ischemic stroke: CT- &gt;3 hours: 64-85%; &gt;6 hours: 47 - 80%; &lt;48 hours: 23-81%; MRI - &gt;6 hours: 65%; &lt;48 hours: 84-88%.</longtext>
				</long>
			</snip>
			<snip id="6">
				<sniptext>MRI is more sensitive than CT in the diagnosis of hemorrhagic or ischemic stroke greater than 1 week after symptom onset.</sniptext>
				<sor type="B">based on 1 high-quality prospective cohort study</sor>
				<long id="6_1">
					<longtext>The HTA performed a prospective cohort study comparing CT with MRI obtained in random order on the day of presentation. They enrolled 228 patients presenting to a general hospital with stroke symptoms: (1) lasting longer than 1 day, but causing little or no decrease in function, or (2) lasting longer than 5 days. The mean time from onset of symptoms to scanning was 21.5 days. CT detected hemorrhagic stroke in 50%, and late hemorrhagic transformation in 20%, of those patients found to have hemorrhagic stroke on MRI, which was considered the criterion standard of chronic stroke diagnosis. The earliest hemorrhagic stroke missed by CT was 11 days old, and the latest hemorrhage correctly identified by CT was 14 days old.</longtext>
				</long>
			</snip>
		</answer>
	</record>
	<record id="1949">
		<url>http://www.jfponline.com/Pages.asp?AID=1949&amp;issue=June_2005&amp;UID=</url>
		<question>What is the best strategy for impaired glucose tolerance in nonpregnant adults?</question>
		<answer>
			<snip id="1">
				<sniptext>The best treatment strategy for impaired glucose tolerance IGT and impaired fasting glucose IFG is lifestyle intervention with a structured weight loss program of diet and exercise. Patients with IGT and IFG should be counseled to lose 5% to 7% of their body weight and instructed on moderate intensity physical activity for ~150 minutes per week.</sniptext>
				<sor type="B">based on high-quality randomized controlled trials [RCTs] for disease-oriented outcomes</sor>
				<long id="1_2">
					<longtext>In the Finnish Diabetes Prevention Study, the lifestyle intervention group had a 12.5% absolute risk reduction compared with the control group (NNT=8). Successful lifestyle interventions included weight loss of 5% to 7%, decreased fat intake, increased fiber intake, and 150 minutes of exercise per week.</longtext>
					<ref id="11333990" abstract="Abstracts/11333990.xml">Tuomilehto J, Lindstrom J, Eriksson JG, et al. Prevention of type 2 diabetes mellitus by changes in lifestyle among subjects with impaired glucose tolerance. N Engl J Med 2001; 344: 1343-1350.</ref>
				</long>
				<long id="1_1">
					<longtext>In the US Diabetes Prevention Program (DPP), 3234 patients with IGT and a body-mass index (BMI) of at least 24 kg/m2 were randomly assigned to one of the following groups: placebo, metformin, or intensive lifestyle modification. After an average follow-up of 2.8 years, there was a 14% absolute risk reduction in the progression to diabetes in the lifestyle intervention group compared with placebo (number needed to treat [NNT]=7). Successful lifestyle interventions included weight loss of 5% to 7%, decreased fat intake, increased fiber intake, and 150 minutes of exercise per week.</longtext>
					<ref id="11832527" abstract="Abstracts/11832527.xml">Knowler WC, Barrett-Connor E, Fowler SE, et al. Reduction in the incidence of type 2 diabetes with lifestyle intervention or metformin. N Engl J Med 2002; 346: 393-403.</ref>
				</long>
			</snip>
			<snip id="2">
				<sniptext>Metformin Glucophage, acarbose Precose, and troglitazone Rezulin are also effective, but lifestyle interventions appear superior. The American Diabetes Association defines IFG as a fasting glucose of between 100 and 125 mg/dL, and IGT as glucose between 140 and 199 mg/dL after a 2-hour oral glucose challenge.</sniptext>
				<sor type="B">based on single high quality randomized controlled trials</sor>
				<long id="2_1">
					<longtext>In the placebo-controlled DPP trial, metformin use was associated with a reduction in progression to diabetes mellitus (NNT=14).</longtext>
					<ref id="11832527" abstract="Abstracts/11832527.xml">Knowler WC, Barrett-Connor E, Fowler SE, et al. Reduction in the incidence of type 2 diabetes with lifestyle intervention or metformin. N Engl J Med 2002; 346: 393-403.</ref>
				</long>
				<long id="2_2">
					<longtext>In the STOP-NIDDM trial of 1429 persons over 3.3 years of follow-up, acarbose 100 mg 3 times daily resulted in a 9% reduction of progression to diabetes, compared with placebo (NNT=11)</longtext>
					<ref id="12086760" abstract="Abstracts/12086760.xml">Chiasson JL, Josse RG, Gomis R, Hanefeld M, Karasik A, Laakso M. Acarbose for prevention of type 2 diabetes mellitus: the STOP-NIDDM randomised trial. Lancet 2002; 359: 2072-2077.</ref>
				</long>
				<long id="2_3">
					<longtext>In the TRIPOD study, troglitazone use was associated with a 17% absolute risk reduction in the incidence of diabetes in high-risk Hispanic women (NNT=6 over an average of 30 months). The preventive effect of the drug was maintained more than 8 months after troglitazone therapy was discontinued (due to withdrawal from the US market). Current trials with other thiazolidinediones are underway.</longtext>
					<ref id="12196473" abstract="Abstracts/12196473.xml">Buchanan TA, Xiang AH, Peters RK, et al. Preservation of pancreatic beta-cell function and prevention of type 2 diabetes by pharmacological treatment of insulin resistance in high-risk hispanic women. Diabetes 2002; 51: 2796-2803.</ref>
				</long>
			</snip>
			<snip id="3">
				<sniptext>Adults with IGT or IFG should have laboratory screening for diabetes every 1 to 2 years, using the fasting plasma glucose FPG as a screening test. For individuals whose FPG exceeds 125 mg/dL, oral glucose tolerance testing is considered superior to glycohemoglobin testing for ruling out progression to diabetes.</sniptext>
				<sor type="C">based on expert opinion</sor>
			</snip>
			<snip id="4">
				<sniptext>For individuals whose FPG exceeds 125 mg/dL, oral glucose tolerance testing is considered superior to glycohemoglobin testing for ruling out progression to diabetes.</sniptext>
				<sor type="C">based on expert opinion</sor>
			</snip>
		</answer>
	</record>
	<record id="5825">
		<url>http://www.jfponline.com/Pages.asp?AID=5825&amp;issue=January_2008&amp;UID=</url>
		<question>What is the most effective and safe malaria prophylaxis during pregnancy?</question>
		<answer>
			<snip id="1">
				<sniptext>Chloroquine and mefloquine have superior safety profiles in pregnancy, though all antimalarials are effective for prophylaxis. Antimalarials will decrease the severity of maternal malaria infection and malaria-associated anemia, while decreasing the incidence of low birth weight and perinatal death in women having their first or second baby.</sniptext>
				<sor type="A">based on systematic review of consistent, good-quality patient-oriented evidence</sor>
				<long id="1_2">
					<longtext>WHO recommends chloroquine as first-line prophylaxis in pregnancy plus proguanil if the region exhibits emerging chloroquine resistance. In areas with proven chloroquine resistance, mefloquine is the drug of choice. Other antimalarials-such as quinine, pyrimethamine, sulfadoxine, and artesunate-should not be withheld if the preferred drugs are not available, or if the infection is life-threatening.</longtext>
					<ref id="5825_2_NOT_FOUND" abstract="Abstracts/NO_ABSTRACT">Malaria. In: International Travel and Health. Geneva, Switzerland: World Health Organization; 2007. Available at: href=http://whqlibdoc.who.int/publications/2005/9241580364_chap7.pdf. Accessed on December 7, 2007.</ref>
				</long>
				<long id="1_1">
					<longtext>Antimalarials were found to decrease the incidence of maternal infections relative risk [RR]=0.27; 95% confidence interval [CI], 0.17-0.44 and reduce maternal anemia RR=0.62; 95% CI, 0.50-0.78 in low-parity women-ie, during a first or second pregnancy.</longtext>
					<ref id="16034957" abstract="Abstracts/16034957.xml">Orton L, Garner P. Drugs for treating uncomplicated malaria in pregnant women. Cochrane Database Syst Rev 2005; 3: CD004912.</ref>
				</long>
			</snip>
			<snip id="2">
				<sniptext>You can determine malaria risk and sensitivity of Plasmodium species by country at wwwn.cdc.gov/travel/destinationlist.aspx. Urge women to delay travel until after pregnancy if possible.</sniptext>
				<sor type="C">based on patient-oriented expert opinion</sor>
				<long id="2_1">
					<longtext>The Centers for Disease Control and Prevention CDC also recommends avoiding travel to malaria-endemic regions during pregnancy, but if travel is necessary, the CDC advises use of chloroquine or mefloquine in regions with chloroquine resistance. The CDC discourages the use of atovaquone/proguanil, doxycycline, and primaquine, due to known adverse fetal effects or inadequate experience in pregnancy.</longtext>
					<ref id="5825_6_NOT_FOUND" abstract="Abstracts/NO_ABSTRACT">Centers for Disease Control and Prevention Web site. Diseases: Malaria: Prevention, Pregnant Women, Public Info. Available at: wwwn.cdc.gov/travel/ contentMalariaPregnantPublic.aspx. Accessed on December 7, 2007.</ref>
				</long>
			</snip>
		</answer>
	</record>
	<record id="5824">
		<url>http://www.jfponline.com/Pages.asp?AID=5824&amp;issue=January_2008&amp;UID=</url>
		<question>Does screening reduce lung cancer mortality?</question>
		<answer>
			<snip id="1">
				<sniptext>It&apos;s not clear. Neither routine chest x-ray (with or without sputum cytology) nor low-dose computed tomography (CT) have been proven to reduce mortality when used for lung cancer screening, although low-dose CT screening does identify lung cancer at an early stage in high-risk patients.</sniptext>
				<sor type="B">based on heterogeneous cohort studies</sor>
				<long id="1_3">
					<longtext>A cohort study using annual CT scanning to screen 3246 patients for lung cancer came to a different conclusion. The authors compared the observed number of lung cancer cases, resections, advanced lung cancer diagnoses, and deaths in screened patients with the expected rates based on validated prediction models. Lung cancer was diagnosed in 144 patients compared with 44 expected cases (RR=3.2; 95% CI, 2.7-3.8). Subsequently, 109 patients underwent lung resection compared with 11 expected (RR=10.0; 95% CI, 8.2-11.9). However, there was no decline in advanced cancers (42 actual vs 33 expected; P=.14) and no difference in deaths due to lung cancer (38 actual vs 38.8 expected; P=.9). The 81 patients diagnosed in this study with stage I disease who underwent surgical resection had 4-year estimated survival rates of 94% (95% CI, 85%-97%), matching the prior low-dose CT study.</longtext>
					<ref id="17341709" abstract="Abstracts/17341709.xml">Bach PB, Jett JR, Pastorino U, Tockman MS, Swensen SJ, Begg CB. Computed tomography screening and Lung cancer outcomes. JAMA. 2008; 279: 953-961.</ref>
				</long>
				<long id="1_2">
					<longtext>A 2006 study followed a cohort of at-risk patients using low-dose CT screening. There were 31,567 patients evaluated initially, of which 27,456 had an annual repeat screening. Most patients were current or former smokers (83%); patients with exposure to occupational and secondhand smoke were also included. A positive initial screen was defined as a solid or partly solid noncalcified nodule ≥5 mm in diameter; a nonsolid, noncalcified nodule ≥8 mm in diameter; or a solid endobronchial nodule. A positive screen during follow-up was defined as any new noncalcified nodule, regardless of size. Positive tests occurred in 13% of baseline screens and 5% of annual screens. Biopsies were performed according to a study protocol based on a nodule&apos;s size and behavior over time. Out of a total of 5646 positive screens, there were 535 biopsies, and a diagnosis of cancer in 492 patients. Of those with cancer, 412 (84%) had clinical stage I lung cancer; the authors estimated their 10-year survival rate was 88% (95% CI, 84%-91%). If patients with stage I disease underwent surgical resection within 1 month of diagnosis, their estimated 10-year survival increased to 92% (95% CI, 88%-95%).</longtext>
					<ref id="17065637" abstract="Abstracts/17065637.xml">The International Early Lung Cancer Action Program Investigators; Henschke CI Yankelevitz DF Libby DM Pasmantier MW Smith JP, Miettinen OS. Survival of patients with stage I lung cancer detected on CT Screening. N Engl J Med. 2006; 355: 1763-1771.</ref>
				</long>
				<long id="1_1">
					<longtext>A Cochrane review identified 6 randomized controlled trials (RCTs) and 1 non-RCT (with a total of 245,610 patients) that screened patients with serial chest x-rays, with or without sputum cytology. Most patients were current or ex-smokers or had significant exposure to industrial smoke. No studies included an unscreened control group, and only 1 included women. Positive tests occurred in 13% of baseline screens and 5% of annual screens. Biopsies were performed according to a study protocol based on a nodule&apos;s size and behavior over time. Out of a total of 5646 positive screens, there were 535 biopsies, and a diagnosis of cancer in 492 patients. Of those with cancer, 412 (84%) had clinical stage I lung cancer; the authors estimated their 10-year survival rate was 88% (95% CI, 84%-91%). If patients with stage I disease underwent surgical resection within 1 month of diagnosis, their estimated 10-year survival increased to 92% (95% CI, 88%-95%).</longtext>
					<ref id="14973979" abstract="Abstracts/14973979.xml">Manser RL, Irving LB, Stone C, Byrnes G, Abramson M, Campbell D. Screening for lung cancer. Cochrane Database System Rev. 2004; 1: CD001991.</ref>
				</long>
			</snip>
		</answer>
	</record>
	<record id="5827">
		<url>http://www.jfponline.com/Pages.asp?AID=5827&amp;issue=January_2008&amp;UID=</url>
		<question>What are the most effective nonpharmacologic therapies for irritable bowel syndrome?</question>
		<answer>
			<snip id="1">
				<sniptext>Herbal formulations, certain probiotics, elimination diets based on immunoglobulin G IgG antibodies, cognitive behavioral therapy, and self-help books have been shown to decrease global symptoms of irritable bowel syndrome IBS and improve overall quality of life.</sniptext>
				<sor type="B">None</sor>
				<long id="1_3">
					<longtext>One RCT compared the probiotic formula Bifidobacterium infantis 35624 with Lactobacillus and placebo, and found that IBS symptom scores and quality of life measures were better with the Bifidobacterium preparation (P&lt;.05).</longtext>
					<ref id="15765388" abstract="Abstracts/15765388.xml">O&apos;Mahony L, McCarthy J, Kelly P, et al. Lactobacillus and bifidobacterium in irritable bowel syndrome: symptom responses and relationship to cytokine profiles. Gastroenterology 2005; 128: 541-551.</ref>
				</long>
				<long id="1_2">